apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: helloocp-route
  namespace: drb-hello
spec:
  host: fritest.apps.drb-4420-18sept.cp.fyre.ibm.com
  path: /hello-ocp
  port:
    targetPort: 8080
  to:
    kind: Service
    name: ifre-test-helloocp-service
    weight: 100
  wildcardPolicy: None
